# Loads default set of integrations. Do not remove.
default_config:

# Home Assistant configuration
homeassistant:
  # Time zone configuration - New Zealand
  time_zone: Pacific/Auckland



# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

# Automations managed through UI (automations.yaml)
script: !include scripts.yaml  
scene: !include scenes.yaml

# Input helpers for scheduling controls
input_text: !include input_text_daily_times.yaml

# Template sensors for enhanced pump status (optional - ESPHome already provides status)
template: !include template.yaml
