esphome:
  name: "floodshelfheight"
  friendly_name: Flood Irrigation Shelf Height
  min_version: 2025.8.0
  name_add_mac_suffix: false

esp32:
  board: esp32dev
  framework:
    type: arduino

logger:
  level: DEBUG

api:
ota:
  - platform: esphome

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

# Load VL6180X custom component
external_components:
  - source: github://Nick6464/vl6180x-esphome
    components: [ vl6180x ]
    refresh: 0s  # Force refresh from GitHub

i2c:
  sda: GPIO21
  scl: GPIO22
  scan: true
  frequency: 400kHz

sensor:
  - platform: vl6180x
    name: "ToF Distance"
    id: tof_distance
    update_interval: 0.5s
    samples: 10  

button:
  - platform: restart
    name: "Restart ESP32"
