esphome:
  name: "tof-test"
  friendly_name: ToF Laser Sensor Test
  min_version: 2025.8.0

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:
  level: DEBUG

# Enable Home Assistant API
api:

# Allow Over-The-Air updates
ota:
  - platform: esphome

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

# I2C Bus Configuration
# Using GPIO21 (SDA) and GPIO22 (SCL) - these are the default I2C pins for ESP32
# Alternative safe option that doesn't conflict with your pumps
i2c:
  sda: GPIO21
  scl: GPIO22
  scan: true
  id: bus_a

# VL53L0X Time-of-Flight Laser Distance Sensor
# This is the most common ToF sensor - adjust if you have a different model
sensor:
  # VL53L0X sensor
  - platform: vl53l0x
    name: "ToF Distance"
    id: tof_distance
    update_interval: 1s
    address: 0x29
    # Timeout for readings (optional)
    timeout: 200ms
    # Measurement timing budget (higher = more accurate but slower)
    # Options: 20ms, 33ms, 50ms, 100ms, 200ms, 500ms
    signal_rate_limit: 0.1
    long_range: false
    icon: mdi:ruler
    unit_of_measurement: "m"
    accuracy_decimals: 3
    filters:
      # Remove any failed readings
      - filter_out: nan
      # Optional: Convert to cm if preferred
      - multiply: 100
      - median:
          window_size: 5
          send_every: 1
    on_value:
      then:
        - logger.log:
            format: "Distance: %.2f cm"
            args: ['x']

  # If you have a VL53L1X (longer range version), use this instead:
  # Uncomment the section below and comment out the VL53L0X section above
  
  # - platform: vl53l1x
  #   name: "ToF Distance"
  #   id: tof_distance
  #   update_interval: 1s
  #   address: 0x29
  #   icon: mdi:ruler
  #   unit_of_measurement: "m"
  #   accuracy_decimals: 3
  #   filters:
  #     - filter_out: nan
  #     - multiply: 100  # Convert to cm
  #     - median:
  #         window_size: 5
  #         send_every: 1

# Status LED (built-in LED on most ESP32 boards)
status_led:
  pin:
    number: GPIO2
    inverted: false

# Test button to trigger a single reading
button:
  - platform: template
    name: "Test ToF Reading"
    id: test_reading
    on_press:
      - logger.log: "Taking ToF measurement..."
      - component.update: tof_distance

